# Generated by Django 5.2.3 on 2025-06-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Цитата', max_length=1000)),
                ('source', models.TextField(help_text='Источник', max_length=150)),
                ('weight', models.FloatField(help_text='Вес частоты')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
    ]
