# Generated by Django 5.2.3 on 2025-06-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0, help_text='Число просмотров'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0, help_text='Число дизлайков цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0, help_text='Число лайков цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.TextField(help_text='Источник, автор', max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(help_text='Текст цитаты', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.FloatField(help_text='Вес частоты появления'),
        ),
    ]
