# Generated by Django 5.2.3 on 2025-07-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotehub', '0002_quote_views_alter_quote_dislikes_alter_quote_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.TextField(help_text='Источник, автор', max_length=120),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(help_text='Текст цитаты', max_length=550),
        ),
        migrations.CreateModel(
            name='QuoteDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotehub.quote')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'quote_id')},
            },
        ),
        migrations.CreateModel(
            name='QuoteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotehub.quote')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'quote_id')},
            },
        ),
        migrations.CreateModel(
            name='QuoteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotehub.quote')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'quote_id')},
            },
        ),
    ]
