# Generated by Django 5.2.3 on 2025-07-02 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotehub', '0003_alter_quote_source_alter_quote_text_quotedislike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotedislike',
            old_name='quote_id',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='quotedislike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='quotelike',
            old_name='quote_id',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='quotelike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='quoteview',
            old_name='quote_id',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='quoteview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='quotedislike',
            unique_together={('user', 'quote')},
        ),
        migrations.AlterUniqueTogether(
            name='quotelike',
            unique_together={('user', 'quote')},
        ),
        migrations.AlterUniqueTogether(
            name='quoteview',
            unique_together={('user', 'quote')},
        ),
    ]
