# Generated by Django 5.2.3 on 2025-07-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotehub', '0004_rename_quote_id_quotedislike_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='views',
        ),
    ]
